### ISSUE TITLE
크루 대시보드의 각 멤버별 풀이 제출 현황 조회 api의 {activity_id}가 해당 크루의 것인지 판단할 수 있는 변수가 필요합니다.

### ISSUE THREAD

**Issue by Whatdoyumin** [tle-ko/be-django#23]
현재 api로 만약 crew_id가 1인 크루의 대시보드를 접속했을 때, 등록된 회차가 "1회차" "2회차"가 있을 경우 activity_id가 1인 정보는 해당 크루의 데이터가 맞지만, activity_id가 2인 정보는 해당 크루의 데이터가 아니어도 표시됩니다.
![1회차 현황표](https://github.com/user-attachments/assets/8d32f783-a276-445e-a0ab-32513aa6c75e)
![2회차](https://github.com/user-attachments/assets/37db7e42-133d-440a-a5f1-7b8e04cc9110)

**Comment by Whatdoyumin** [comment]
crew_id가 필요할 것 같아 보입니다.

**Comment by hepheir** [comment]
해당 내용은 새로운 API가 필요한것이 아닌 버그로 보입니다. 제출 현황 조회에 해당 크루의 것만 나타나도록 수정하되 새로운 기능은 추가하지 않겠습니다.
