### ISSUE TITLE
크루 대시보드 회차별 등록된 문제 조회 API가 필요합니다.

### ISSUE THREAD

**Issue by Whatdoyumin** [tle-ko/be-django#8]
![풀이할 문제](https://github.com/user-attachments/assets/49f4dcac-916b-4929-8ef0-c608bc23bcf6)

**Comment by hepheir** [comment]
#9 와 동일한 API로 두 컴포넌트 모두를 커버할 수 있을 것으로 보입니다.

**Comment by hepheir** [comment]
`/crew/activity/{activity_id}` API에 해당 내용 포함되도록 기능 구현 되었습니다.
